[2023-11-12 14:08:19,143: INFO: main: Welcome to our custom log.]
[2023-11-12 14:13:19,290: INFO: main: Welcome to our custom log.]
[2023-11-14 09:38:23,482: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 09:38:23,487: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 09:38:23,492: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 09:38:23,495: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/utils/common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    data_ingestion.main()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/config/configuration.py", line 17, in __init__
    self.params = read_yaml(params_filepath)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/utils/common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2023-11-14 09:40:41,878: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 09:40:41,884: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 09:40:41,889: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 09:40:41,898: INFO: common: created directory at: artifacts]
[2023-11-14 09:40:41,905: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 09:40:41,907: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 09:41:06,953: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 09:42:25,656: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
